import com.automationanywhere.botcommand.data.Value;
import com.automationanywhere.botcommand.data.impl.DictionaryValue;
import com.automationanywhere.botcommand.data.impl.ListValue;
import com.automationanywhere.botcommand.data.impl.StringValue;
import com.automationanywhere.botcommand.samples.commands.basic.getValue;
import com.automationanywhere.botcommand.samples.commands.basic.xmlToDict;
import com.automationanywhere.botcommand.samples.commands.conditionals.KeysExists;
import com.automationanywhere.botcommand.samples.commands.conditionals.typeValidation;
import com.automationanywhere.botcommand.samples.commands.utils.DictUteis;
import com.automationanywhere.botcommand.samples.commands.utils.JsonUtils;
import org.json.JSONObject;
import org.testng.annotations.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.json.XML;


public class test {
@Test
void xml(){

    xmlToDict a = new xmlToDict();
    String xml ="<?xml version=\"1.0\"?> <CustPortInqRs> <SEQUENCE>07070002</SEQUENCE> <ResponseData> <TOTALACCTS>003</TOTALACCTS> <PENDINGCNT>000</PENDINGCNT> <READCNT>000</READCNT> <BRDCASTCNT>000</BRDCASTCNT><TIMEACCOUNT> <UNDPRELEXT></UNDPRELEXT> <GROUPCD>2</GROUPCD> <GROUPSEQ>999</GROUPSEQ> <APPLCD>CD</APPLCD> <ACTDESC>Certificate</ACTDESC> <ACTNBR>3500003948</ACTNBR> <PRODTYPE>EC1</PRODTYPE> <SHORTNAME>Yabuki, Melissa S</SHORTNAME> <OFFICER>000</OFFICER> <BRANCH>007</BRANCH> <RELTYPE>SOL</RELTYPE> <PRIMARYFLG>Y</PRIMARYFLG> <TXRSPENT>Y</TXRSPENT> <PCTOWNED>0</PCTOWNED> <OWNERTYPE>D</OWNERTYPE> <INTERFLG>Y</INTERFLG> <IVRFLG>Y</IVRFLG> <CURINTRATE>.2996</CURINTRATE> <ACTSTATUS>O</ACTSTATUS> <CURRBAL>0</CURRBAL> <AVAILBAL>30000.00</AVAILBAL> <PAYOFFAMT>0</PAYOFFAMT> <INTPDYTD>0</INTPDYTD> <INTPDLSTYR>0</INTPDLSTYR> <INTACCRUED>0</INTACCRUED> <DTOPENED>20220418</DTOPENED> <DTCLOSED>0</DTCLOSED> <DTLSTSTMT>0</DTLSTSTMT> <LSTINTPD>0</LSTINTPD> <TOTHOLDS>0</TOTHOLDS> <ANTICPEN>0</ANTICPEN> <AMOUNT04>0</AMOUNT04> <AMOUNT05>0</AMOUNT05> <AMOUNT06>0</AMOUNT06> <AMOUNT07>0</AMOUNT07> <AMOUNT08>0</AMOUNT08> <AMOUNT09>0</AMOUNT09> <AMOUNT10>30000.00</AMOUNT10> <AMOUNT11>0</AMOUNT11> <AMOUNT12>0</AMOUNT12> <NXTINTPYM1>20220518</NXTINTPYM1> <LSTINTPYMT>0</LSTINTPYMT> <CURMTRYDT>20230418</CURMTRYDT> <DATE04>0</DATE04> <LSTRNWLDT>0</LSTRNWLDT> <DATE06>0</DATE06> <DATE07>0</DATE07> <NXTINTPYM2>20220518</NXTINTPYM2> <PLANNBR>0</PLANNBR> <PLANTYPE></PLANTYPE> <MISC03></MISC03> <FUTURE01></FUTURE01> <PORTTOTFLG></PORTTOTFLG> <PCTALWDFLG></PCTALWDFLG> <OCDSTATUS>O</OCDSTATUS> <CONFFLAG>N</CONFFLAG> <CASHMGMT1>N</CASHMGMT1> <CASHMGMT2>N</CASHMGMT2> <REGDRSTINT></REGDRSTINT> <FUTURE02>0</FUTURE02> <PREAUTTRCT>0</PREAUTTRCT> <OPTION1></OPTION1> <OPTION2></OPTION2> <BILLPAYFLG></BILLPAYFLG> <AMOUNT13>0</AMOUNT13> <RRSSELFLG>N</RRSSELFLG> <DYAVAILFLG>N</DYAVAILFLG> <DDAVAILFLG>N</DDAVAILFLG> <LNAVAILFLG>N</LNAVAILFLG> <ODLIMITFLG>N</ODLIMITFLG> <CUSTFLTFLG>N</CUSTFLTFLG> <BNKFLTFLG>N</BNKFLTFLG> <HOLDSFLG>N</HOLDSFLG> <CKPDTDYFLG>N</CKPDTDYFLG> <AMOUNT14>0</AMOUNT14> <AMOUNT15>0</AMOUNT15> <AMOUNT16>0</AMOUNT16> <AMOUNT17>0</AMOUNT17> <AMOUNT18>0</AMOUNT18> <DATE09>0</DATE09> <DATE10>0</DATE10> <PRODUCT>E-CD 1 YEAR</PRODUCT> <MISC05>Yabuki, Melissa S</MISC05> <MISC06></MISC06> <MISC07></MISC07> </TIMEACCOUNT> <DEPACCOUNT> <UNDPRELEXT></UNDPRELEXT> <GROUPCD>2</GROUPCD> <GROUPSEQ>999</GROUPSEQ> <APPLCD>DD</APPLCD> <ACTDESC>Demand Dep</ACTDESC> <ACTNBR>1000203354</ACTNBR> <PRODTYPE>PGG</PRODTYPE> <SHORTNAME>Yabuki, Melissa S</SHORTNAME> <OFFICER>000</OFFICER> <BRANCH>007</BRANCH> <RELTYPE>SOL</RELTYPE> <PRIMARYFLG>Y</PRIMARYFLG> <TXRSPENT>Y</TXRSPENT> <PCTOWNED>0</PCTOWNED> <OWNERTYPE>D</OWNERTYPE> <INTERFLG>Y</INTERFLG> <IVRFLG>Y</IVRFLG> <CURINTRATE>0</CURINTRATE> <ACTSTATUS>6</ACTSTATUS> <CURRBAL>40000.00</CURRBAL> <AVAILBAL>10000.00</AVAILBAL> <PAYOFFAMT>40000.00</PAYOFFAMT> <INTPDYTD>0</INTPDYTD> <INTPDLSTYR>0</INTPDLSTYR> <INTACCRUED>0</INTACCRUED> <DTOPENED>20220408</DTOPENED> <DTCLOSED>0</DTCLOSED> <DTLSTSTMT>0</DTLSTSTMT> <LSTINTAMTP>0</LSTINTAMTP> <HOLDAMT>0</HOLDAMT> <CHKDEPTDY>0</CHKDEPTDY> <TBNKFLTAMT>0</TBNKFLTAMT> <TCUSTFLTAM>0</TCUSTFLTAM> <CRLMTAMT>0</CRLMTAMT> <RRSCURBAL>0</RRSCURBAL> <COLLBAL>40000.00</COLLBAL> <AMTLSTDEP>40000.00</AMTLSTDEP> <CTFAVABAL>10000.00</CTFAVABAL> <RUNCURBAL>10000.00</RUNCURBAL> <AVCOLBALPY>0</AVCOLBALPY> <LSTODDT>0</LSTODDT> <PVBGSTMDT1>0</PVBGSTMDT1> <PVEDSTMDT1>0</PVEDSTMDT1> <PVBGSTMDT2>0</PVBGSTMDT2> <PVEDSTMDT2>0</PVEDSTMDT2> <PVBGSTMDT3>0</PVBGSTMDT3> <PVEDSTMDT3>0</PVEDSTMDT3> <PVBGSTMDT4>0</PVBGSTMDT4> <MISC01>0</MISC01> <PASSBOOKCD></PASSBOOKCD> <STMTCYCCD>ME</STMTCYCCD> <FUTURE01></FUTURE01> <PORTTOTFLG></PORTTOTFLG> <PCTALWDFLG></PCTALWDFLG> <OCDSTATUS>O</OCDSTATUS> <CONFFLAG>N</CONFFLAG> <CASHMGMT1>N</CASHMGMT1> <CASHMGMT2>N</CASHMGMT2> <REGDRSTINT>N</REGDRSTINT> <FUTURE02>0</FUTURE02> <PREAUTTRCT>0</PREAUTTRCT> <ENCOPTSTMT>I</ENCOPTSTMT> <ENCOPTNTC>N</ENCOPTNTC> <BILLPAYFLG></BILLPAYFLG> <LNCRLIMIT>0</LNCRLIMIT> <RRSSELFLG>N</RRSSELFLG> <DYAVAILFLG></DYAVAILFLG> <DDAVAILFLG>Y</DDAVAILFLG> <LNAVAILFLG>N</LNAVAILFLG> <ODLIMITFLG>N</ODLIMITFLG> <CUSTFLTFLG>N</CUSTFLTFLG> <BNKFLTFLG>N</BNKFLTFLG> <HOLDSFLG>Y</HOLDSFLG> <CKPDTDYFLG>N</CKPDTDYFLG> <RRSAVABAL>0</RRSAVABAL> <DYNAVABAL>0</DYNAVABAL> <DDSVAVABAL>10000.00</DDSVAVABAL> <LNAVABAL>0</LNAVABAL> <ODLIMITBAL>0</ODLIMITBAL> <DATE09>20220418</DATE09> <DATE10>20220418</DATE10> <PRODUCT>PERSONAL GOLD GLOBAL</PRODUCT> <MISC05>Yabuki, Melissa S</MISC05> <MISC06></MISC06> <MISC07></MISC07> </DEPACCOUNT> <DEPACCOUNT> <UNDPRELEXT></UNDPRELEXT> <GROUPCD>2</GROUPCD> <GROUPSEQ>999</GROUPSEQ> <APPLCD>DD</APPLCD> <ACTDESC>Demand Dep</ACTDESC> <ACTNBR>1000203362</ACTNBR> <PRODTYPE>PMM</PRODTYPE> <SHORTNAME>Yabuki, Melissa S</SHORTNAME> <OFFICER>000</OFFICER> <BRANCH>007</BRANCH> <RELTYPE>SOL</RELTYPE> <PRIMARYFLG>Y</PRIMARYFLG> <TXRSPENT>Y</TXRSPENT> <PCTOWNED>0</PCTOWNED> <OWNERTYPE>D</OWNERTYPE> <INTERFLG>Y</INTERFLG> <IVRFLG>Y</IVRFLG> <CURINTRATE>.1000</CURINTRATE> <ACTSTATUS>6</ACTSTATUS> <CURRBAL>0</CURRBAL> <AVAILBAL>0</AVAILBAL> <PAYOFFAMT>0</PAYOFFAMT> <INTPDYTD>0</INTPDYTD> <INTPDLSTYR>0</INTPDLSTYR> <INTACCRUED>0</INTACCRUED> <DTOPENED>20220408</DTOPENED> <DTCLOSED>0</DTCLOSED> <DTLSTSTMT>0</DTLSTSTMT> <LSTINTAMTP>0</LSTINTAMTP> <HOLDAMT>0</HOLDAMT> <CHKDEPTDY>0</CHKDEPTDY> <TBNKFLTAMT>0</TBNKFLTAMT> <TCUSTFLTAM>0</TCUSTFLTAM> <CRLMTAMT>0</CRLMTAMT> <RRSCURBAL>0</RRSCURBAL> <COLLBAL>0</COLLBAL> <AMTLSTDEP>0</AMTLSTDEP> <CTFAVABAL>0</CTFAVABAL> <RUNCURBAL>0</RUNCURBAL> <AVCOLBALPY>0</AVCOLBALPY> <LSTODDT>0</LSTODDT> <PVBGSTMDT1>0</PVBGSTMDT1> <PVEDSTMDT1>0</PVEDSTMDT1> <PVBGSTMDT2>0</PVBGSTMDT2> <PVEDSTMDT2>0</PVEDSTMDT2> <PVBGSTMDT3>0</PVBGSTMDT3> <PVEDSTMDT3>0</PVEDSTMDT3> <PVBGSTMDT4>0</PVBGSTMDT4> <MISC01>0</MISC01> <PASSBOOKCD></PASSBOOKCD> <STMTCYCCD>ME</STMTCYCCD> <FUTURE01></FUTURE01> <PORTTOTFLG></PORTTOTFLG> <PCTALWDFLG></PCTALWDFLG> <OCDSTATUS>O</OCDSTATUS> <CONFFLAG>N</CONFFLAG> <CASHMGMT1>N</CASHMGMT1> <CASHMGMT2>N</CASHMGMT2> <REGDRSTINT>Y</REGDRSTINT> <FUTURE02>0</FUTURE02> <PREAUTTRCT>0</PREAUTTRCT> <ENCOPTSTMT>I</ENCOPTSTMT> <ENCOPTNTC>N</ENCOPTNTC> <BILLPAYFLG></BILLPAYFLG> <LNCRLIMIT>0</LNCRLIMIT> <RRSSELFLG>N</RRSSELFLG> <DYAVAILFLG></DYAVAILFLG> <DDAVAILFLG>Y</DDAVAILFLG> <LNAVAILFLG>N</LNAVAILFLG> <ODLIMITFLG>N</ODLIMITFLG> <CUSTFLTFLG>N</CUSTFLTFLG> <BNKFLTFLG>N</BNKFLTFLG> <HOLDSFLG>Y</HOLDSFLG> <CKPDTDYFLG>N</CKPDTDYFLG> <RRSAVABAL>0</RRSAVABAL> <DYNAVABAL>0</DYNAVABAL> <DDSVAVABAL>0</DDSVAVABAL> <LNAVABAL>0</LNAVABAL> <ODLIMITBAL>0</ODLIMITBAL> <DATE09>0</DATE09> <DATE10>0</DATE10> <PRODUCT>PERSONAL MONEY MARKET</PRODUCT> <MISC05>Yabuki, Melissa S</MISC05> <MISC06></MISC06> <MISC07></MISC07> </DEPACCOUNT><RECS_RETURNED>0003</RECS_RETURNED><MOREDATA>N</MOREDATA></ResponseData> </CustPortInqRs>";
    String fl = "C:\\Users\\melque\\Documents\\xmls.xml";

   DictionaryValue dct =  a.action(fl,true);

   String aa = "";

}
    void teste(){
    KeysExists act = new KeysExists();
    getValue gv = new getValue();
    typeValidation tv = new typeValidation();


    String xml ="<?xml version=\"1.0\"?> <CustPortInqRs> <SEQUENCE>07070002</SEQUENCE> <ResponseData> <TOTALACCTS>003</TOTALACCTS> <PENDINGCNT>000</PENDINGCNT> <READCNT>000</READCNT> <BRDCASTCNT>000</BRDCASTCNT><TIMEACCOUNT> <UNDPRELEXT></UNDPRELEXT> <GROUPCD>2</GROUPCD> <GROUPSEQ>999</GROUPSEQ> <APPLCD>CD</APPLCD> <ACTDESC>Certificate</ACTDESC> <ACTNBR>3500003948</ACTNBR> <PRODTYPE>EC1</PRODTYPE> <SHORTNAME>Yabuki, Melissa S</SHORTNAME> <OFFICER>000</OFFICER> <BRANCH>007</BRANCH> <RELTYPE>SOL</RELTYPE> <PRIMARYFLG>Y</PRIMARYFLG> <TXRSPENT>Y</TXRSPENT> <PCTOWNED>0</PCTOWNED> <OWNERTYPE>D</OWNERTYPE> <INTERFLG>Y</INTERFLG> <IVRFLG>Y</IVRFLG> <CURINTRATE>.2996</CURINTRATE> <ACTSTATUS>O</ACTSTATUS> <CURRBAL>0</CURRBAL> <AVAILBAL>30000.00</AVAILBAL> <PAYOFFAMT>0</PAYOFFAMT> <INTPDYTD>0</INTPDYTD> <INTPDLSTYR>0</INTPDLSTYR> <INTACCRUED>0</INTACCRUED> <DTOPENED>20220418</DTOPENED> <DTCLOSED>0</DTCLOSED> <DTLSTSTMT>0</DTLSTSTMT> <LSTINTPD>0</LSTINTPD> <TOTHOLDS>0</TOTHOLDS> <ANTICPEN>0</ANTICPEN> <AMOUNT04>0</AMOUNT04> <AMOUNT05>0</AMOUNT05> <AMOUNT06>0</AMOUNT06> <AMOUNT07>0</AMOUNT07> <AMOUNT08>0</AMOUNT08> <AMOUNT09>0</AMOUNT09> <AMOUNT10>30000.00</AMOUNT10> <AMOUNT11>0</AMOUNT11> <AMOUNT12>0</AMOUNT12> <NXTINTPYM1>20220518</NXTINTPYM1> <LSTINTPYMT>0</LSTINTPYMT> <CURMTRYDT>20230418</CURMTRYDT> <DATE04>0</DATE04> <LSTRNWLDT>0</LSTRNWLDT> <DATE06>0</DATE06> <DATE07>0</DATE07> <NXTINTPYM2>20220518</NXTINTPYM2> <PLANNBR>0</PLANNBR> <PLANTYPE></PLANTYPE> <MISC03></MISC03> <FUTURE01></FUTURE01> <PORTTOTFLG></PORTTOTFLG> <PCTALWDFLG></PCTALWDFLG> <OCDSTATUS>O</OCDSTATUS> <CONFFLAG>N</CONFFLAG> <CASHMGMT1>N</CASHMGMT1> <CASHMGMT2>N</CASHMGMT2> <REGDRSTINT></REGDRSTINT> <FUTURE02>0</FUTURE02> <PREAUTTRCT>0</PREAUTTRCT> <OPTION1></OPTION1> <OPTION2></OPTION2> <BILLPAYFLG></BILLPAYFLG> <AMOUNT13>0</AMOUNT13> <RRSSELFLG>N</RRSSELFLG> <DYAVAILFLG>N</DYAVAILFLG> <DDAVAILFLG>N</DDAVAILFLG> <LNAVAILFLG>N</LNAVAILFLG> <ODLIMITFLG>N</ODLIMITFLG> <CUSTFLTFLG>N</CUSTFLTFLG> <BNKFLTFLG>N</BNKFLTFLG> <HOLDSFLG>N</HOLDSFLG> <CKPDTDYFLG>N</CKPDTDYFLG> <AMOUNT14>0</AMOUNT14> <AMOUNT15>0</AMOUNT15> <AMOUNT16>0</AMOUNT16> <AMOUNT17>0</AMOUNT17> <AMOUNT18>0</AMOUNT18> <DATE09>0</DATE09> <DATE10>0</DATE10> <PRODUCT>E-CD 1 YEAR</PRODUCT> <MISC05>Yabuki, Melissa S</MISC05> <MISC06></MISC06> <MISC07></MISC07> </TIMEACCOUNT> <DEPACCOUNT> <UNDPRELEXT></UNDPRELEXT> <GROUPCD>2</GROUPCD> <GROUPSEQ>999</GROUPSEQ> <APPLCD>DD</APPLCD> <ACTDESC>Demand Dep</ACTDESC> <ACTNBR>1000203354</ACTNBR> <PRODTYPE>PGG</PRODTYPE> <SHORTNAME>Yabuki, Melissa S</SHORTNAME> <OFFICER>000</OFFICER> <BRANCH>007</BRANCH> <RELTYPE>SOL</RELTYPE> <PRIMARYFLG>Y</PRIMARYFLG> <TXRSPENT>Y</TXRSPENT> <PCTOWNED>0</PCTOWNED> <OWNERTYPE>D</OWNERTYPE> <INTERFLG>Y</INTERFLG> <IVRFLG>Y</IVRFLG> <CURINTRATE>0</CURINTRATE> <ACTSTATUS>6</ACTSTATUS> <CURRBAL>40000.00</CURRBAL> <AVAILBAL>10000.00</AVAILBAL> <PAYOFFAMT>40000.00</PAYOFFAMT> <INTPDYTD>0</INTPDYTD> <INTPDLSTYR>0</INTPDLSTYR> <INTACCRUED>0</INTACCRUED> <DTOPENED>20220408</DTOPENED> <DTCLOSED>0</DTCLOSED> <DTLSTSTMT>0</DTLSTSTMT> <LSTINTAMTP>0</LSTINTAMTP> <HOLDAMT>0</HOLDAMT> <CHKDEPTDY>0</CHKDEPTDY> <TBNKFLTAMT>0</TBNKFLTAMT> <TCUSTFLTAM>0</TCUSTFLTAM> <CRLMTAMT>0</CRLMTAMT> <RRSCURBAL>0</RRSCURBAL> <COLLBAL>40000.00</COLLBAL> <AMTLSTDEP>40000.00</AMTLSTDEP> <CTFAVABAL>10000.00</CTFAVABAL> <RUNCURBAL>10000.00</RUNCURBAL> <AVCOLBALPY>0</AVCOLBALPY> <LSTODDT>0</LSTODDT> <PVBGSTMDT1>0</PVBGSTMDT1> <PVEDSTMDT1>0</PVEDSTMDT1> <PVBGSTMDT2>0</PVBGSTMDT2> <PVEDSTMDT2>0</PVEDSTMDT2> <PVBGSTMDT3>0</PVBGSTMDT3> <PVEDSTMDT3>0</PVEDSTMDT3> <PVBGSTMDT4>0</PVBGSTMDT4> <MISC01>0</MISC01> <PASSBOOKCD></PASSBOOKCD> <STMTCYCCD>ME</STMTCYCCD> <FUTURE01></FUTURE01> <PORTTOTFLG></PORTTOTFLG> <PCTALWDFLG></PCTALWDFLG> <OCDSTATUS>O</OCDSTATUS> <CONFFLAG>N</CONFFLAG> <CASHMGMT1>N</CASHMGMT1> <CASHMGMT2>N</CASHMGMT2> <REGDRSTINT>N</REGDRSTINT> <FUTURE02>0</FUTURE02> <PREAUTTRCT>0</PREAUTTRCT> <ENCOPTSTMT>I</ENCOPTSTMT> <ENCOPTNTC>N</ENCOPTNTC> <BILLPAYFLG></BILLPAYFLG> <LNCRLIMIT>0</LNCRLIMIT> <RRSSELFLG>N</RRSSELFLG> <DYAVAILFLG></DYAVAILFLG> <DDAVAILFLG>Y</DDAVAILFLG> <LNAVAILFLG>N</LNAVAILFLG> <ODLIMITFLG>N</ODLIMITFLG> <CUSTFLTFLG>N</CUSTFLTFLG> <BNKFLTFLG>N</BNKFLTFLG> <HOLDSFLG>Y</HOLDSFLG> <CKPDTDYFLG>N</CKPDTDYFLG> <RRSAVABAL>0</RRSAVABAL> <DYNAVABAL>0</DYNAVABAL> <DDSVAVABAL>10000.00</DDSVAVABAL> <LNAVABAL>0</LNAVABAL> <ODLIMITBAL>0</ODLIMITBAL> <DATE09>20220418</DATE09> <DATE10>20220418</DATE10> <PRODUCT>PERSONAL GOLD GLOBAL</PRODUCT> <MISC05>Yabuki, Melissa S</MISC05> <MISC06></MISC06> <MISC07></MISC07> </DEPACCOUNT> <DEPACCOUNT> <UNDPRELEXT></UNDPRELEXT> <GROUPCD>2</GROUPCD> <GROUPSEQ>999</GROUPSEQ> <APPLCD>DD</APPLCD> <ACTDESC>Demand Dep</ACTDESC> <ACTNBR>1000203362</ACTNBR> <PRODTYPE>PMM</PRODTYPE> <SHORTNAME>Yabuki, Melissa S</SHORTNAME> <OFFICER>000</OFFICER> <BRANCH>007</BRANCH> <RELTYPE>SOL</RELTYPE> <PRIMARYFLG>Y</PRIMARYFLG> <TXRSPENT>Y</TXRSPENT> <PCTOWNED>0</PCTOWNED> <OWNERTYPE>D</OWNERTYPE> <INTERFLG>Y</INTERFLG> <IVRFLG>Y</IVRFLG> <CURINTRATE>.1000</CURINTRATE> <ACTSTATUS>6</ACTSTATUS> <CURRBAL>0</CURRBAL> <AVAILBAL>0</AVAILBAL> <PAYOFFAMT>0</PAYOFFAMT> <INTPDYTD>0</INTPDYTD> <INTPDLSTYR>0</INTPDLSTYR> <INTACCRUED>0</INTACCRUED> <DTOPENED>20220408</DTOPENED> <DTCLOSED>0</DTCLOSED> <DTLSTSTMT>0</DTLSTSTMT> <LSTINTAMTP>0</LSTINTAMTP> <HOLDAMT>0</HOLDAMT> <CHKDEPTDY>0</CHKDEPTDY> <TBNKFLTAMT>0</TBNKFLTAMT> <TCUSTFLTAM>0</TCUSTFLTAM> <CRLMTAMT>0</CRLMTAMT> <RRSCURBAL>0</RRSCURBAL> <COLLBAL>0</COLLBAL> <AMTLSTDEP>0</AMTLSTDEP> <CTFAVABAL>0</CTFAVABAL> <RUNCURBAL>0</RUNCURBAL> <AVCOLBALPY>0</AVCOLBALPY> <LSTODDT>0</LSTODDT> <PVBGSTMDT1>0</PVBGSTMDT1> <PVEDSTMDT1>0</PVEDSTMDT1> <PVBGSTMDT2>0</PVBGSTMDT2> <PVEDSTMDT2>0</PVEDSTMDT2> <PVBGSTMDT3>0</PVBGSTMDT3> <PVEDSTMDT3>0</PVEDSTMDT3> <PVBGSTMDT4>0</PVBGSTMDT4> <MISC01>0</MISC01> <PASSBOOKCD></PASSBOOKCD> <STMTCYCCD>ME</STMTCYCCD> <FUTURE01></FUTURE01> <PORTTOTFLG></PORTTOTFLG> <PCTALWDFLG></PCTALWDFLG> <OCDSTATUS>O</OCDSTATUS> <CONFFLAG>N</CONFFLAG> <CASHMGMT1>N</CASHMGMT1> <CASHMGMT2>N</CASHMGMT2> <REGDRSTINT>Y</REGDRSTINT> <FUTURE02>0</FUTURE02> <PREAUTTRCT>0</PREAUTTRCT> <ENCOPTSTMT>I</ENCOPTSTMT> <ENCOPTNTC>N</ENCOPTNTC> <BILLPAYFLG></BILLPAYFLG> <LNCRLIMIT>0</LNCRLIMIT> <RRSSELFLG>N</RRSSELFLG> <DYAVAILFLG></DYAVAILFLG> <DDAVAILFLG>Y</DDAVAILFLG> <LNAVAILFLG>N</LNAVAILFLG> <ODLIMITFLG>N</ODLIMITFLG> <CUSTFLTFLG>N</CUSTFLTFLG> <BNKFLTFLG>N</BNKFLTFLG> <HOLDSFLG>Y</HOLDSFLG> <CKPDTDYFLG>N</CKPDTDYFLG> <RRSAVABAL>0</RRSAVABAL> <DYNAVABAL>0</DYNAVABAL> <DDSVAVABAL>0</DDSVAVABAL> <LNAVABAL>0</LNAVABAL> <ODLIMITBAL>0</ODLIMITBAL> <DATE09>0</DATE09> <DATE10>0</DATE10> <PRODUCT>PERSONAL MONEY MARKET</PRODUCT> <MISC05>Yabuki, Melissa S</MISC05> <MISC06></MISC06> <MISC07></MISC07> </DEPACCOUNT><RECS_RETURNED>0003</RECS_RETURNED><MOREDATA>N</MOREDATA></ResponseData> </CustPortInqRs>";

    JSONObject response = XML.toJSONObject(xml,true);
    Map<String, Value> v =  JsonUtils.JsonObjToMapValue(response);
    String srch = "CustPortInqRs.ResponseData.DEPACCOUNT.ACTDESC";


    DictionaryValue d = dic();
    System.out.println("================== Value:" + act.validate(v,srch,"exists"));
    Value a = gv.action(d.get(),"b");
    System.out.println("================== Value2:" + tv.validate(a,"string","match"));


    //Boolean a = act.validate("test","equals",lista);
    System.out.println("================== Value:" + act.validate(d.get(),"b","exists"));
}

    DictionaryValue dic(){
        DictionaryValue ret = new DictionaryValue();
        DictionaryValue ts = new DictionaryValue();
        DictionaryValue ts2 = new DictionaryValue();
        ListValue<String> ListVal = new ListValue<String>();
        List<Value> CTRL = new ArrayList<Value>();
        Map<String, Value> vvv = new HashMap<>();


        vvv.put("aa",new StringValue("11"));
        vvv.put("bb",new StringValue("22"));
        vvv.put("cc",new StringValue("33"));
        ts2.set(vvv);



        CTRL.add(new StringValue("A"));
        CTRL.add(ts2);
        ListVal.set(CTRL);


        Map<String, Value> v = new HashMap<>();


        v.put("a",ListVal);
        v.put("b",new StringValue("2"));
        v.put("c",new StringValue("3"));

        ts.set(v);


        Map<String, Value> vv = new HashMap<>();

        vv.put("a",ts);
        vv.put("b",ListVal);
        vv.put("c",new StringValue("3"));



        ret.set(vv);
        return ret;
    }

}
